### ISSUE TITLE
criar um .h para os pinos

### ISSUE THREAD

**Issue by rafaelcorsi** [JoseFernandoInsper/apsMusical#1]
https://github.com/JoseFernandoInsper/apsMusical/blob/ca3db1a8e03ba74237a053c8b5ada9c7eecc97a6/TC-RTC-IRQ/TC-RTC-IRQ/src/main.c#L16-L55

criar um arquivo ( 'io.h') e colocar todos os defines de pino

**Comment by JoseFernandoInsper** [comment]
done
