### ISSUE TITLE
limpar código

### ISSUE THREAD

**Issue by rafaelcorsi** [JoseFernandoInsper/apsMusical#2]
exe: 

https://github.com/JoseFernandoInsper/apsMusical/blob/ca3db1a8e03ba74237a053c8b5ada9c7eecc97a6/TC-RTC-IRQ/TC-RTC-IRQ/src/main.c#L1

https://github.com/JoseFernandoInsper/apsMusical/blob/ca3db1a8e03ba74237a053c8b5ada9c7eecc97a6/TC-RTC-IRQ/TC-RTC-IRQ/src/main.c#L281

**Comment by JoseFernandoInsper** [comment]
done
